## docker-compose.yml
version: "3.8"

services:
  staff-records:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - test_network

  pgadmin4:
    build:
      context: .
      dockerfile: dockerfile.pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "openforme"
    ports:
      - "5067:80"
    depends_on:
      - staff-records
    networks:
      - test_network
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin/data

  web:
    build: ./app
    # command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port=8000"
    #command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - ./app/Config/app.env
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}"
    restart: always
    depends_on:
      - staff-records
    volumes:
      - ./app:/app
    ports:
      - 8081:8080
    networks:
      - test_network

networks:
  test_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
